CREATE TABLE maladies (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    malady_name TEXT NOT NULL,
    malady_symptoms TEXT NOT NULL,
    malady_description TEXT NOT NULL,
    userid INTEGER REFERENCES users(id)
)