CREATE TABLE likes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userid INTEGER REFERENCES users(id)  NOT NULL,
    remedyid INTEGER REFERENCES remedies(id) on delete cascade NOT NULL,
    liked BOOLEAN
) 