INSERT INTO maladies (malady_name, malady_symptoms, malady_description)
VALUES
    ('Hypertension','Severe headache, fatigue or confusion, vision problems, difficulty breathing, irregular heartbeat, blood in the urin, pounding in neck, chest or ears', 'High blood pressure'),
    ('Hyperlipidemia', 'Few symptoms', 'A disorder resluting in extra fats (lipids) in your blood. High cholesterol is an example.- must be diagnosed with a blood test. The AHA (American Heart Association) recommends that adults 20 and older get the cholesterol checked every 4-6 years. Total cholesterol of 200 mg/dl or more is out of the normal range.'),
    ('Diabetes', 'Hunger and fatigue, peeing more often and being thirstier, dry-mout, itchy skin, blurred vision','Diabetes is a disorder of metabolism -- the way our bodies use digested food for growth and energy.'),
    ('Back Pain', 'Pain in the low back or sides, inflexibility', 'Back pain includes lower back pain, middle back pain, upper back pain or low back pain with sciatica. Nerve and muscular problems, degenerative disc disease, and arthritis can result in back pain.'),
    ('Anxiety', 'Sudden overwhelming fear, palpitations, sweating, trembling, shortness of breath, sense of choking, chest pain, nausea, dizziness, a feeling of being detached, difficulty sleeping', 'Anxiety is your body''s natural response to stress. In the case of an anxiety disorder, the feeling of fear may be with you all the time. It is intense and sometimes debilitating.'),
    ('Obesity', 'Weight gain, overeating','Being obese means having so much body fat that your health is in danger. Having too much body fat can lead to type 2 diabetes, heart disease, high blood pressure, arthritis, sleep apnea, and stroke.'),
    ('Hay fever','runny or stuffy nose, sneezing, red, itchy and watery eyes, and swelling around the eyes', 'Hay fever or allergic rhinitis is a type of inflammation in the nose which occurs when the immune system overreacts to allergens in the air.')
 
